name: CI

on: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run type checking
        run: npm run type-check
        
      - name: Run linting
        run: npm run lint:check
        
      - name: Build project
        run: npm run build
        
      - name: Run tests
        run: npm run test
        
      # Upload build artifacts for main branch
      - name: Upload build artifacts
        if: github.ref == 'refs/heads/main' && matrix.node-version == '20'
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/
          
  # Security and quality checks
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - name: Run security audit
        run: npm audit --audit-level high
